
package proyecto;

import javax.swing.JOptionPane;


public class NuevoCliente extends javax.swing.JDialog {

    /**
     * Creates new form NuevoCliente
     */
    public NuevoCliente(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNuevoDni = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtNuevoNom = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtNuevoApe = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnAceptarNue = new javax.swing.JButton();
        btnCancelarNue = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Nuevo Cliente");
        setResizable(false);

        txtNuevoDni.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNuevoDniFocusLost(evt);
            }
        });
        txtNuevoDni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNuevoDniActionPerformed(evt);
            }
        });

        jLabel1.setText("DNI");

        jLabel2.setText("nom");

        jLabel3.setText("ape");

        btnAceptarNue.setText("Aceptar");
        btnAceptarNue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarNueActionPerformed(evt);
            }
        });

        btnCancelarNue.setText("Salir");
        btnCancelarNue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarNueActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(32, 32, 32)
                            .addComponent(txtNuevoDni, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3))
                            .addGap(32, 32, 32)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtNuevoApe, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtNuevoNom, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(btnAceptarNue)
                        .addGap(18, 18, 18)
                        .addComponent(btnCancelarNue)))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNuevoDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(txtNuevoNom, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(txtNuevoApe, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCancelarNue)
                    .addComponent(btnAceptarNue))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarNueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarNueActionPerformed
       
        String newdni=txtNuevoDni.getText();
        String newnombre=txtNuevoNom.getText();
        String newape = txtNuevoApe.getText();
 
        Cliente clie = new Cliente();
        clie.setDni(Integer.parseInt(newdni));
        clie.setNombres(newnombre);
        clie.setApellidos(newape);
        Principal.cc.agregarCliente(clie);
        Principal.cboDNI.removeAllElements();
        for(int i=0;i<Principal.cc.getnClientes();i++){
            Principal.cboDNI.addElement(Principal.cc.obtenerCliente(i).getDni());
        }
        
        Principal.cboDniClie.setModel(Principal.cboDNI);
        txtNuevoDni.setText(" ");
        txtNuevoNom.setText(" ");
        txtNuevoApe.setText(" ");
        txtNuevoDni.requestFocus();
        // TODO add your handling code here:
 
    }//GEN-LAST:event_btnAceptarNueActionPerformed

    private void btnCancelarNueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarNueActionPerformed

        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelarNueActionPerformed

    private void txtNuevoDniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNuevoDniActionPerformed
        
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNuevoDniActionPerformed

    private void txtNuevoDniFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNuevoDniFocusLost

        String dniclie = txtNuevoDni.getText();
        for(int i=0; i< Principal.cc.getnClientes();i++){
            if(Principal.cc.obtenerCliente(i).getDni()== Integer.parseInt(dniclie)){
                JOptionPane.showMessageDialog(this, "El DNI: "+ dniclie + "ya existe.","Validacion",JOptionPane.ERROR_MESSAGE );
                txtNuevoDni.setText(" ");
                txtNuevoDni.setFocusable(true);
            }
        }
        
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNuevoDniFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NuevoCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NuevoCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NuevoCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NuevoCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                NuevoCliente dialog = new NuevoCliente(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptarNue;
    private javax.swing.JButton btnCancelarNue;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtNuevoApe;
    private javax.swing.JTextField txtNuevoDni;
    private javax.swing.JTextField txtNuevoNom;
    // End of variables declaration//GEN-END:variables
}
